/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerList implements Serializable {

    private static final long serialVersionUID = -1908139038;

    private Integer id;
    private String  name;
    private String  address;
    private String  zipCode;
    private String  phone;
    private String  city;
    private String  country;
    private String  notes;
    private Short   sid;

    public CustomerList() {}

    public CustomerList(CustomerList value) {
        this.id = value.id;
        this.name = value.name;
        this.address = value.address;
        this.zipCode = value.zipCode;
        this.phone = value.phone;
        this.city = value.city;
        this.country = value.country;
        this.notes = value.notes;
        this.sid = value.sid;
    }

    public CustomerList(
        Integer id,
        String  name,
        String  address,
        String  zipCode,
        String  phone,
        String  city,
        String  country,
        String  notes,
        Short   sid
    ) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.zipCode = zipCode;
        this.phone = phone;
        this.city = city;
        this.country = country;
        this.notes = notes;
        this.sid = sid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Short getSid() {
        return this.sid;
    }

    public void setSid(Short sid) {
        this.sid = sid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerList (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(address);
        sb.append(", ").append(zipCode);
        sb.append(", ").append(phone);
        sb.append(", ").append(city);
        sb.append(", ").append(country);
        sb.append(", ").append(notes);
        sb.append(", ").append(sid);

        sb.append(")");
        return sb.toString();
    }
}
