/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmInStock implements Serializable {

    private static final long serialVersionUID = -1999151597;

    private Integer pFilmCount;

    public FilmInStock() {}

    public FilmInStock(FilmInStock value) {
        this.pFilmCount = value.pFilmCount;
    }

    public FilmInStock(
        Integer pFilmCount
    ) {
        this.pFilmCount = pFilmCount;
    }

    public Integer getPFilmCount() {
        return this.pFilmCount;
    }

    public void setPFilmCount(Integer pFilmCount) {
        this.pFilmCount = pFilmCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmInStock (");

        sb.append(pFilmCount);

        sb.append(")");
        return sb.toString();
    }
}
