/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesByStore implements Serializable {

    private static final long serialVersionUID = 1286458009;

    private String     store;
    private String     manager;
    private BigDecimal totalSales;

    public SalesByStore() {}

    public SalesByStore(SalesByStore value) {
        this.store = value.store;
        this.manager = value.manager;
        this.totalSales = value.totalSales;
    }

    public SalesByStore(
        String     store,
        String     manager,
        BigDecimal totalSales
    ) {
        this.store = store;
        this.manager = manager;
        this.totalSales = totalSales;
    }

    public String getStore() {
        return this.store;
    }

    public void setStore(String store) {
        this.store = store;
    }

    public String getManager() {
        return this.manager;
    }

    public void setManager(String manager) {
        this.manager = manager;
    }

    public BigDecimal getTotalSales() {
        return this.totalSales;
    }

    public void setTotalSales(BigDecimal totalSales) {
        this.totalSales = totalSales;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SalesByStore (");

        sb.append(store);
        sb.append(", ").append(manager);
        sb.append(", ").append(totalSales);

        sb.append(")");
        return sb.toString();
    }
}
