/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.daos;


import com.bisaga.sakila.dbmodel.tables.Address;
import com.bisaga.sakila.dbmodel.tables.records.AddressRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressDao extends DAOImpl<AddressRecord, com.bisaga.sakila.dbmodel.tables.pojos.Address, Integer> {

    /**
     * Create a new AddressDao without any configuration
     */
    public AddressDao() {
        super(Address.ADDRESS, com.bisaga.sakila.dbmodel.tables.pojos.Address.class);
    }

    /**
     * Create a new AddressDao with an attached configuration
     */
    public AddressDao(Configuration configuration) {
        super(Address.ADDRESS, com.bisaga.sakila.dbmodel.tables.pojos.Address.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.bisaga.sakila.dbmodel.tables.pojos.Address object) {
        return object.getAddressId();
    }

    /**
     * Fetch records that have <code>address_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByAddressId(Integer... values) {
        return fetch(Address.ADDRESS.ADDRESS_ID, values);
    }

    /**
     * Fetch a unique record that has <code>address_id = value</code>
     */
    public com.bisaga.sakila.dbmodel.tables.pojos.Address fetchOneByAddressId(Integer value) {
        return fetchOne(Address.ADDRESS.ADDRESS_ID, value);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByAddress(String... values) {
        return fetch(Address.ADDRESS.ADDRESS_, values);
    }

    /**
     * Fetch records that have <code>address2 IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByAddress2(String... values) {
        return fetch(Address.ADDRESS.ADDRESS2, values);
    }

    /**
     * Fetch records that have <code>district IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByDistrict(String... values) {
        return fetch(Address.ADDRESS.DISTRICT, values);
    }

    /**
     * Fetch records that have <code>city_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByCityId(Short... values) {
        return fetch(Address.ADDRESS.CITY_ID, values);
    }

    /**
     * Fetch records that have <code>postal_code IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByPostalCode(String... values) {
        return fetch(Address.ADDRESS.POSTAL_CODE, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByPhone(String... values) {
        return fetch(Address.ADDRESS.PHONE, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Address> fetchByLastUpdate(Timestamp... values) {
        return fetch(Address.ADDRESS.LAST_UPDATE, values);
    }
}
