/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.daos;


import com.bisaga.sakila.dbmodel.tables.Category;
import com.bisaga.sakila.dbmodel.tables.records.CategoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryDao extends DAOImpl<CategoryRecord, com.bisaga.sakila.dbmodel.tables.pojos.Category, Integer> {

    /**
     * Create a new CategoryDao without any configuration
     */
    public CategoryDao() {
        super(Category.CATEGORY, com.bisaga.sakila.dbmodel.tables.pojos.Category.class);
    }

    /**
     * Create a new CategoryDao with an attached configuration
     */
    public CategoryDao(Configuration configuration) {
        super(Category.CATEGORY, com.bisaga.sakila.dbmodel.tables.pojos.Category.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.bisaga.sakila.dbmodel.tables.pojos.Category object) {
        return object.getCategoryId();
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Category> fetchByCategoryId(Integer... values) {
        return fetch(Category.CATEGORY.CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>category_id = value</code>
     */
    public com.bisaga.sakila.dbmodel.tables.pojos.Category fetchOneByCategoryId(Integer value) {
        return fetchOne(Category.CATEGORY.CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Category> fetchByName(String... values) {
        return fetch(Category.CATEGORY.NAME, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Category> fetchByLastUpdate(Timestamp... values) {
        return fetch(Category.CATEGORY.LAST_UPDATE, values);
    }
}
