/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.daos;


import com.bisaga.sakila.dbmodel.tables.Inventory;
import com.bisaga.sakila.dbmodel.tables.records.InventoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryDao extends DAOImpl<InventoryRecord, com.bisaga.sakila.dbmodel.tables.pojos.Inventory, Integer> {

    /**
     * Create a new InventoryDao without any configuration
     */
    public InventoryDao() {
        super(Inventory.INVENTORY, com.bisaga.sakila.dbmodel.tables.pojos.Inventory.class);
    }

    /**
     * Create a new InventoryDao with an attached configuration
     */
    public InventoryDao(Configuration configuration) {
        super(Inventory.INVENTORY, com.bisaga.sakila.dbmodel.tables.pojos.Inventory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.bisaga.sakila.dbmodel.tables.pojos.Inventory object) {
        return object.getInventoryId();
    }

    /**
     * Fetch records that have <code>inventory_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Inventory> fetchByInventoryId(Integer... values) {
        return fetch(Inventory.INVENTORY.INVENTORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>inventory_id = value</code>
     */
    public com.bisaga.sakila.dbmodel.tables.pojos.Inventory fetchOneByInventoryId(Integer value) {
        return fetchOne(Inventory.INVENTORY.INVENTORY_ID, value);
    }

    /**
     * Fetch records that have <code>film_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Inventory> fetchByFilmId(Short... values) {
        return fetch(Inventory.INVENTORY.FILM_ID, values);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Inventory> fetchByStoreId(Short... values) {
        return fetch(Inventory.INVENTORY.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Inventory> fetchByLastUpdate(Timestamp... values) {
        return fetch(Inventory.INVENTORY.LAST_UPDATE, values);
    }
}
