/*
 * This file is generated by jOOQ.
*/
package com.bisaga.sakila.dbmodel.tables.daos;


import com.bisaga.sakila.dbmodel.tables.Store;
import com.bisaga.sakila.dbmodel.tables.records.StoreRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreDao extends DAOImpl<StoreRecord, com.bisaga.sakila.dbmodel.tables.pojos.Store, Integer> {

    /**
     * Create a new StoreDao without any configuration
     */
    public StoreDao() {
        super(Store.STORE, com.bisaga.sakila.dbmodel.tables.pojos.Store.class);
    }

    /**
     * Create a new StoreDao with an attached configuration
     */
    public StoreDao(Configuration configuration) {
        super(Store.STORE, com.bisaga.sakila.dbmodel.tables.pojos.Store.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.bisaga.sakila.dbmodel.tables.pojos.Store object) {
        return object.getStoreId();
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Store> fetchByStoreId(Integer... values) {
        return fetch(Store.STORE.STORE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>store_id = value</code>
     */
    public com.bisaga.sakila.dbmodel.tables.pojos.Store fetchOneByStoreId(Integer value) {
        return fetchOne(Store.STORE.STORE_ID, value);
    }

    /**
     * Fetch records that have <code>manager_staff_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Store> fetchByManagerStaffId(Short... values) {
        return fetch(Store.STORE.MANAGER_STAFF_ID, values);
    }

    /**
     * Fetch records that have <code>address_id IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Store> fetchByAddressId(Short... values) {
        return fetch(Store.STORE.ADDRESS_ID, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<com.bisaga.sakila.dbmodel.tables.pojos.Store> fetchByLastUpdate(Timestamp... values) {
        return fetch(Store.STORE.LAST_UPDATE, values);
    }
}
